type PortalUiLang = "pt-BR" | "en" | "es-419" | "zh-CN";

const localeMap: Record<PortalUiLang, string> = {
  "pt-BR": "pt-BR",
  en: "en-US",
  "es-419": "es-419",
  "zh-CN": "zh-CN",
};

function resolveLanguage(language?: string): PortalUiLang {
  if (language?.startsWith("pt")) return "pt-BR";
  if (language?.startsWith("es")) return "es-419";
  if (language?.startsWith("zh")) return "zh-CN";
  return "en";
}

const copy: Record<PortalUiLang, Record<string, string>> = {
  "pt-BR": {
    unavailableFile: "Arquivo indisponível.", loadingCase: "Carregando atendimento…", back: "Voltar",
    customerReport: "Relato do cliente", expectedBehavior: "Comportamento esperado", notProvided: "Não informado", software: "Software", carrier: "Operadora", category: "Categoria", systemApps: "Sistema e aplicativos", hardware: "Hardware",
    evidence: "Evidências", noEvidence: "Nenhum arquivo enviado ainda.", download: "Baixar", addFile: "Adicionar arquivo", uploadingFile: "Enviando {{name}} · {{progress}}%", uploadFailed: "Não foi possível enviar o arquivo. Tente novamente sem sair desta página.", computerEvidence: "Coletas pelo computador", captureSessions: "Sessões de captura", noCaptureSessions: "Nenhuma coleta pelo computador associada.",
    supportCase: "Atendimento", customer: "Cliente", email: "E-mail", receivedAt: "Recebido em", owner: "Responsável", unassigned: "Ainda não atribuído", status: "Status", priority: "Prioridade", assign: "Atribuir",
    updates: "Atualizações", caseReceived: "Caso recebido", dataUpdated: "Dados atualizados", visibleUpdate: "Atualização visível ao cliente", publishUpdate: "Publicar atualização", nextStepTitle: "O que acontece agora", nextReceived: "Recebemos seu caso. Nenhuma ação é necessária agora; vamos iniciar a análise das informações enviadas.", nextReviewing: "Seu caso está em análise. Mantenha seus canais de contato disponíveis caso a equipe precise confirmar alguma informação.", nextAwaitingCustomer: "Precisamos de uma informação sua. Veja a atualização mais recente abaixo e adicione a evidência solicitada, se necessário.", nextResolved: "Este atendimento foi concluído. Consulte as atualizações abaixo para ver a resolução informada.",
    warrantyData: "Triagem de garantia", warrantyStatus: "Possível garantia", warrantyYes: "Sim", warrantyNo: "Não", warrantyUnsure: "Não informado / não tenho certeza", deviceIdentifier: "IMEI / número de série", purchaseDate: "Data da compra", replyTitle: "Responder ao suporte", replyText: "Escreva a informação solicitada pela equipe. Você também pode adicionar uma evidência acima, se necessário.", replyPlaceholder: "Digite sua resposta aqui…", sendReply: "Enviar resposta", replySending: "Enviando…", replySent: "Resposta enviada. Nossa equipe poderá continuar a análise por este atendimento.", replyFailed: "Não foi possível enviar sua resposta. Tente novamente sem sair desta página.", customerReplyLabel: "Resposta do cliente",
    trackingEyebrow: "ACOMPANHAMENTO", trackingTitle: "Seu caso, por aqui.", trackingText: "Use os dados recebidos ao finalizar o atendimento.", protocol: "Protocolo", accessCode: "Código de acesso", viewCase: "Consultar caso",
    staffArea: "ÁREA DA EQUIPE", helloTfae: "Olá, equipe.", staffIntro: "Acesse os atendimentos e as evidências de acordo com seu perfil.", staffEmail: "E-mail corporativo", password: "Senha", signingIn: "Entrando…", accessDashboard: "Acessar painel", sendCode: "Enviar código", sendingCode: "Enviando código…", codeSentTitle: "Código enviado", codeSentText: "Enviamos um código de 6 dígitos para este e-mail. Ele expira em 10 minutos.", staffAccessCode: "Código de acesso", codeDigitsHint: "Digite os 6 números recebidos por e-mail.", verifyCode: "Validar e entrar", verifyingCode: "Validando…", trustDevice: "Confiar neste dispositivo por 7 dias", trustDeviceHint: "Use apenas em um computador pessoal ou corporativo de uso exclusivo. Após 7 dias, um novo código será solicitado.", resendCode: "Reenviar código", useDifferentEmail: "Usar outro e-mail", authRequestFailed: "Não foi possível enviar o código agora. Tente novamente.", authVerifyFailed: "Código inválido, expirado ou bloqueado. Solicite um novo código e tente novamente.", emailCodeUnavailable: "O acesso por código de e-mail ainda não está configurado. Use a senha temporariamente.", authPasswordFailed: "Não foi possível entrar com essas credenciais.", emergencyAccess: "Acesso de contingência", emergencyAccessTitle: "Acesso de contingência TFAE", emergencyAccessText: "Use este acesso somente se o código por e-mail não estiver disponível. A credencial deve ser mantida com segurança pela equipe.", backToEmailCode: "Voltar ao código por e-mail",
    workspaceEyebrow: "BRTE WORKSPACE / VISÃO GERAL", workspaceTitle: "Cada caso merece atenção.", workspaceIntro: "Organize a análise. Conecte as evidências. Acompanhe a solução.", signedInAs: "Conectado como", roleTfae: "TFAE", roleManager: "Manager", managerReadOnlyTitle: "Acesso de acompanhamento", managerReadOnlyText: "Como Manager, você pode acompanhar casos, responsáveis, evidências e histórico. Alterações operacionais permanecem com os TFAEs.", logout: "Sair",
    totalCases: "Total de casos", awaitingAnalysis: "Aguardando análise", inReview: "Em análise", resolvedCases: "Resolvidos", teamMonitoring: "Acompanhamento dos TFAEs", activeCases: "casos ativos", assignedCases: "atribuídos", caseCenter: "Central de atendimentos", refresh: "Atualizar", filterStatus: "Filtrar status", all: "Todos",
    searchCases: "Buscar casos", searchPlaceholder: "Buscar caso, modelo, cliente…", caseProblem: "CASO / PROBLEMA", device: "APARELHO", received: "RECEBIDO", openCase: "Abrir {{problem}}",
    noSearchResults: "Nenhum caso corresponde à busca.", readyFirstCase: "Tudo pronto para o primeiro atendimento.", tryAnotherSearch: "Experimente outro termo ou filtro.", casesWillAppear: "Os casos enviados pelos clientes aparecerão aqui.",
    priorityNormal: "Normal", priorityHigh: "Alta", priorityUrgent: "Urgente",
    statusReceived: "Recebido", statusReviewing: "Em análise", statusAwaitingCustomer: "Aguardando cliente", statusResolved: "Resolvido", statusRecording: "Gravando", statusComplete: "Concluída", statusPartial: "Evidência parcial", statusFailed: "Falha na coleta", statusInterrupted: "Captura interrompida", statusAwaitingYlog: "Aguardando parada dos logs", statusFinalizing: "Finalizando", statusStarting: "Iniciando",
    assistedEyebrow: "DIAGNÓSTICO ASSISTIDO", assistedTitle: "Seu celular. Nossa atenção.", assistedIntro: "Reproduza o problema enquanto reunimos as informações para análise.", localConnected: "Suporte local conectado", waitingConnection: "Aguardando conexão",
    connectStep: "01 / CONECTAR", prepareComputer: "Prepare o computador.", prepareComputerText: "Abra o Support Bridge no Windows e conecte o celular com um cabo USB de dados.", installBridge: "Instalar e abrir o Support Bridge", initialSetup: "Configuração inicial no computador", connectionCode: "Código de conexão do programa", connectionCodePlaceholder: "Cole o código exibido ao abrir o programa", connect: "Conectar",
    authorizeStep: "02 / AUTORIZAR", connectDevice: "Conecte seu aparelho.", authorizeText: "Ative a depuração USB e aceite a autorização na tela do celular.", viewImageInstructions: "Ver instruções com imagens", noDevice: "Nenhum aparelho detectado", dataCableHint: "Use um cabo de dados e mantenha a tela desbloqueada.", authorizeComputer: "Autorize este computador no aparelho", deviceOffline: "Aparelho offline", authorized: "Autorizado", platform: "Plataforma", unknownPlatform: "Não reconhecida",
    associateStep: "03 / ASSOCIAR AO ATENDIMENTO", oneCaseMany: "Um caso, várias reproduções.", caseProtocol: "Protocolo do caso", caseAccessCode: "Código de acesso ao caso", autoUpload: "Enviar automaticamente as capturas finalizadas para este caso.",
    reproductionArea: "ÁREA DE REPRODUÇÃO", captureRunning: "Captura em andamento", readyToView: "Pronto para visualizar", letsConnect: "Vamos conectar seu celular.", reproduceThenStop: "Reproduza o problema no seu aparelho. Quando terminar, pare a captura.", mirrorText: "A visualização do celular abre em uma janela no seu computador.", openView: "Abrir visualização", ylogStarted: "Já iniciei a coleta de logs no YLog do aparelho.", captureConsent: "Autorizo a gravação da tela e a coleta dos registros técnicos desta reprodução.", startCapture: "Iniciar captura", stopYlogText: "A gravação de tela já parou. Pare os logs no YLog do aparelho para continuar.", ylogStoppedCollect: "Já parei os logs — coletar arquivos", finishingValidating: "Finalizando e validando…", stopSave: "Parar e salvar captura",
    capturesThisComputer: "Capturas deste computador", capturesAppear: "Suas reproduções aparecerão aqui. Cada uma gera um pacote independente.", uploadedTo: "Enviado para {{caseId}}", sendToCase: "Enviar para o caso", noComputerConnection: "Sem computador ou conexão?", continueMobileGuide: "Continue com o guia usando apenas o celular.", localSupportInterrupted: "Conexão com o suporte local interrompida. Verifique o programa no computador.",
    browserAutoAvailable: "Coleta automática disponível no Chrome ou Edge.", browserOpenDesktop: "Abra esta página em um computador usando Chrome ou Microsoft Edge. Nenhuma instalação é necessária.", browserDirect: "COLETA DIRETA PELO NAVEGADOR", connectPhone: "Conecte seu celular", usbHint: "Prepare o aparelho e siga as etapas abaixo para conectar.", beforeConnectTitle: "Antes de conectar", beforeConnectCable: "Use um cabo USB que também transfira dados.", beforeConnectUnlock: "Deixe o celular desbloqueado e mantenha esta página aberta.", beforeConnectPermission: "Quando o celular pedir permissão para esta conexão, aceite para continuar.", beforeConnectHelp: "Se nada aparecer, reconecte o cabo e confira se ele é um cabo de dados.", developerSetupTitle: "Prepare o celular uma vez", developerSetupText: "Para o navegador se conectar ao celular, ative o Modo Desenvolvedor e a Depuração USB. Ativar essas opções não apaga seus arquivos.", developerGuideTitle: "Como ativar o Modo Desenvolvedor e a Depuração USB", developerStep1: "Abra Configurações e entre em Sobre o telefone.", developerStep2: "Toque 7 vezes em Número da versão / Build number até o celular informar que o Modo Desenvolvedor foi ativado.", developerStep3: "Volte para Configurações e abra Sistema → Opções do desenvolvedor. Em alguns modelos, o caminho pode aparecer diretamente em Configurações.", developerStep4: "Ative Depuração USB e confirme a mensagem do Android.", developerStep5: "Conecte o celular ao computador usando um cabo USB que transfira dados.", developerStep6: "Quando aparecer “Permitir depuração USB? / Allow USB debugging?”, toque em Permitir / OK.", developerMenuNote: "Os nomes dos menus podem variar um pouco conforme o modelo e a versão do Android.", developerAfterUse: "Depois do atendimento, você pode desativar a Depuração USB novamente.", tutorialBadge: "TUTORIAL EM VÍDEO", tutorialTitle: "Veja como preparar o celular", tutorialText: "Assista enquanto faz os passos. O vídeo mostra onde ativar a Depuração USB e confirmar o acesso.", tutorialPrivacy: "O vídeo foi recortado para mostrar somente as etapas necessárias.", tutorialLoading: "Preparando o vídeo…", tutorialUnavailable: "O vídeo não pôde ser carregado. Siga os passos escritos ao lado e continue normalmente.", tutorialNoAudio: "O vídeo não tem áudio. Use os passos escritos como referência principal.", connecting: "Conectando…", redoAuthorization: "Tentar conexão novamente",
    maxTwoMinutes: "Limite máximo: 2 minutos.", twoMinuteHint: "Depois de iniciar, reproduza o problema imediatamente e finalize assim que ele acontecer. Ao atingir 2 minutos, a coleta será encerrada automaticamente e será necessário fazer uma nova tentativa.", browserConsent: "Autorizo a gravação da tela e a coleta de registros técnicos somente para analisar este problema.", startCollection: "Iniciar coleta", preparingDiagnosis: "Preparando o diagnóstico. Não use o celular por alguns segundos…", recordingInProgress: "Gravação em andamento", reproduceFinish: "Reproduza o problema no celular. Quando acontecer, volte a esta página e clique em “Terminei”.", warningSeconds: "Atenção: faltam {{seconds}} segundos. A coleta será encerrada automaticamente em 2 minutos.", finished: "Terminei", savingTechnical: "Salvando a gravação e os registros técnicos…", collectionComplete: "Coleta concluída.", filesNextStep: "Os arquivos serão enviados junto com o atendimento na próxima etapa.", technicalDetails: "Detalhes técnicos",
    privacyTitle: "Privacidade BRTE", privacyP1: "Nome, e-mail, telefone, endereço, país, informações do aparelho, IMEI ou número de série e data da compra quando informados, descrição do problema e as evidências escolhidas ficam associados ao atendimento. A coleta assistida pode incluir gravação de tela, registros técnicos e metadados do aparelho.", privacyP2: "Feche conversas pessoais, senhas e documentos antes de gravar. A coleta só começa após sua autorização.", loading: "Carregando…",
  },
  en: {
    unavailableFile: "File unavailable.", loadingCase: "Loading case…", back: "Back",
    customerReport: "Customer report", expectedBehavior: "Expected behavior", notProvided: "Not provided", software: "Software", carrier: "Carrier", category: "Category", systemApps: "System and applications", hardware: "Hardware",
    evidence: "Evidence", noEvidence: "No files have been submitted yet.", download: "Download", addFile: "Add file", uploadingFile: "Uploading {{name}} · {{progress}}%", uploadFailed: "We could not upload the file. Try again without leaving this page.", computerEvidence: "Computer collections", captureSessions: "Capture sessions", noCaptureSessions: "No computer collection is associated with this case.",
    supportCase: "Case", customer: "Customer", email: "Email", receivedAt: "Received at", owner: "Owner", unassigned: "Not assigned yet", status: "Status", priority: "Priority", assign: "Assign",
    updates: "Updates", caseReceived: "Case received", dataUpdated: "Data updated", visibleUpdate: "Update visible to the customer", publishUpdate: "Publish update", nextStepTitle: "What happens next", nextReceived: "We received your case. No action is needed right now; we will begin reviewing the information you sent.", nextReviewing: "Your case is under review. Keep your contact channels available in case the team needs to confirm something.", nextAwaitingCustomer: "We need something from you. Review the latest update below and add the requested evidence if needed.", nextResolved: "This case has been completed. Review the updates below for the resolution provided.",
    warrantyData: "Warranty triage", warrantyStatus: "Possible warranty", warrantyYes: "Yes", warrantyNo: "No", warrantyUnsure: "Not provided / not sure", deviceIdentifier: "IMEI / serial number", purchaseDate: "Purchase date", replyTitle: "Reply to support", replyText: "Send the information the team requested. You can also add evidence above if needed.", replyPlaceholder: "Type your reply here…", sendReply: "Send reply", replySending: "Sending…", replySent: "Reply sent. Our team can continue the review in this case.", replyFailed: "We could not send your reply. Try again without leaving this page.", customerReplyLabel: "Customer reply",
    trackingEyebrow: "CASE TRACKING", trackingTitle: "Your case, right here.", trackingText: "Use the details you received when you submitted the case.", protocol: "Case number", accessCode: "Access code", viewCase: "View case",
    staffArea: "TEAM AREA", helloTfae: "Hello, team.", staffIntro: "Access customer cases and evidence according to your role.", staffEmail: "Corporate email", password: "Password", signingIn: "Signing in…", accessDashboard: "Open dashboard", sendCode: "Send code", sendingCode: "Sending code…", codeSentTitle: "Code sent", codeSentText: "We sent a 6-digit code to this email. It expires in 10 minutes.", staffAccessCode: "Access code", codeDigitsHint: "Enter the 6 digits sent by email.", verifyCode: "Verify and sign in", verifyingCode: "Verifying…", trustDevice: "Trust this device for 7 days", trustDeviceHint: "Use this only on a personal or dedicated corporate computer. After 7 days, a new code will be required.", resendCode: "Resend code", useDifferentEmail: "Use another email", authRequestFailed: "We could not send the code right now. Please try again.", authVerifyFailed: "The code is invalid, expired, or blocked. Request a new code and try again.", emailCodeUnavailable: "Email-code access is not configured yet. Use the password temporarily.", authPasswordFailed: "We could not sign in with those credentials.", emergencyAccess: "Emergency access", emergencyAccessTitle: "TFAE emergency access", emergencyAccessText: "Use this only if the e-mail code service is unavailable. The credential must be securely maintained by the team.", backToEmailCode: "Back to e-mail code",
    workspaceEyebrow: "BRTE WORKSPACE / OVERVIEW", workspaceTitle: "Every case deserves attention.", workspaceIntro: "Organize the analysis. Connect the evidence. Follow the resolution.", signedInAs: "Signed in as", roleTfae: "TFAE", roleManager: "Manager", managerReadOnlyTitle: "Monitoring access", managerReadOnlyText: "As a Manager, you can monitor cases, owners, evidence, and history. Operational changes remain with TFAEs.", logout: "Sign out",
    totalCases: "Total cases", awaitingAnalysis: "Awaiting analysis", inReview: "In review", resolvedCases: "Resolved", teamMonitoring: "TFAE monitoring", activeCases: "active cases", assignedCases: "assigned", caseCenter: "Case center", refresh: "Refresh", filterStatus: "Filter by status", all: "All",
    searchCases: "Search cases", searchPlaceholder: "Search case, model, customer…", caseProblem: "CASE / ISSUE", device: "DEVICE", received: "RECEIVED", openCase: "Open {{problem}}",
    noSearchResults: "No cases match your search.", readyFirstCase: "Ready for the first case.", tryAnotherSearch: "Try another term or filter.", casesWillAppear: "Customer cases will appear here.",
    priorityNormal: "Normal", priorityHigh: "High", priorityUrgent: "Urgent",
    statusReceived: "Received", statusReviewing: "In review", statusAwaitingCustomer: "Awaiting customer", statusResolved: "Resolved", statusRecording: "Recording", statusComplete: "Complete", statusPartial: "Partial evidence", statusFailed: "Collection failed", statusInterrupted: "Capture interrupted", statusAwaitingYlog: "Waiting for logs to stop", statusFinalizing: "Finalizing", statusStarting: "Starting",
    assistedEyebrow: "ASSISTED DIAGNOSTICS", assistedTitle: "Your phone. Our attention.", assistedIntro: "Reproduce the issue while we collect the information needed for analysis.", localConnected: "Local support connected", waitingConnection: "Waiting for connection",
    connectStep: "01 / CONNECT", prepareComputer: "Prepare the computer.", prepareComputerText: "Open Support Bridge on Windows and connect the phone with a USB data cable.", installBridge: "Install and open Support Bridge", initialSetup: "Initial computer setup", connectionCode: "Program connection code", connectionCodePlaceholder: "Paste the code shown when the program opens", connect: "Connect",
    authorizeStep: "02 / AUTHORIZE", connectDevice: "Connect your device.", authorizeText: "Enable USB debugging and accept the authorization on the phone.", viewImageInstructions: "View instructions with images", noDevice: "No device detected", dataCableHint: "Use a data cable and keep the screen unlocked.", authorizeComputer: "Authorize this computer on the device", deviceOffline: "Device offline", authorized: "Authorized", platform: "Platform", unknownPlatform: "Not recognized",
    associateStep: "03 / LINK TO CASE", oneCaseMany: "One case, multiple reproductions.", caseProtocol: "Case number", caseAccessCode: "Case access code", autoUpload: "Automatically upload finalized captures to this case.",
    reproductionArea: "REPRODUCTION AREA", captureRunning: "Capture in progress", readyToView: "Ready to view", letsConnect: "Let's connect your phone.", reproduceThenStop: "Reproduce the issue on the device. When finished, stop the capture.", mirrorText: "The phone view opens in a window on your computer.", openView: "Open view", ylogStarted: "I have already started YLog collection on the device.", captureConsent: "I authorize screen recording and technical log collection for this reproduction.", startCapture: "Start capture", stopYlogText: "Screen recording has stopped. Stop YLog on the device to continue.", ylogStoppedCollect: "I stopped the logs — collect files", finishingValidating: "Finalizing and validating…", stopSave: "Stop and save capture",
    capturesThisComputer: "Captures from this computer", capturesAppear: "Your reproductions will appear here. Each one creates an independent package.", uploadedTo: "Uploaded to {{caseId}}", sendToCase: "Send to case", noComputerConnection: "No computer or connection?", continueMobileGuide: "Continue with the guide using only the phone.", localSupportInterrupted: "Connection to local support was interrupted. Check the program on the computer.",
    browserAutoAvailable: "Automatic collection is available in Chrome or Edge.", browserOpenDesktop: "Open this page on a computer using Chrome or Microsoft Edge. No installation is required.", browserDirect: "DIRECT BROWSER COLLECTION", connectPhone: "Connect your phone", usbHint: "Prepare the phone and follow the steps below to connect.", beforeConnectTitle: "Before connecting", beforeConnectCable: "Use a USB cable that can transfer data.", beforeConnectUnlock: "Keep the phone unlocked and leave this page open.", beforeConnectPermission: "When the phone asks for permission for this connection, accept it to continue.", beforeConnectHelp: "If nothing appears, reconnect the cable and make sure it supports data transfer.", developerSetupTitle: "Prepare your phone once", developerSetupText: "To let the browser connect to your phone, enable Developer Mode and USB debugging. Enabling these options does not erase your files.", developerGuideTitle: "How to enable Developer Mode and USB debugging", developerStep1: "Open Settings and go to About phone.", developerStep2: "Tap Build number 7 times until the phone confirms that Developer Mode is enabled.", developerStep3: "Return to Settings and open System → Developer options. On some models, Developer options appears directly in Settings.", developerStep4: "Enable USB debugging and confirm the Android prompt.", developerStep5: "Connect the phone to the computer using a USB cable that supports data transfer.", developerStep6: "When “Allow USB debugging?” appears, tap Allow / OK.", developerMenuNote: "Menu names can vary slightly by model and Android version.", developerAfterUse: "After the support session, you can turn USB debugging off again.", tutorialBadge: "VIDEO TUTORIAL", tutorialTitle: "See how to prepare your phone", tutorialText: "Watch while following the steps. The video shows where to enable USB debugging and approve access.", tutorialPrivacy: "The video has been trimmed to show only the required steps.", tutorialLoading: "Preparing the video…", tutorialUnavailable: "The video could not be loaded. Follow the written steps and continue normally.", tutorialNoAudio: "The video has no audio. Use the written steps as the main reference.", connecting: "Connecting…", redoAuthorization: "Try connection again",
    maxTwoMinutes: "Maximum limit: 2 minutes.", twoMinuteHint: "After starting, reproduce the issue immediately and finish as soon as it happens. At 2 minutes, collection will stop automatically and you will need to try again.", browserConsent: "I authorize screen recording and technical log collection only to analyze this issue.", startCollection: "Start collection", preparingDiagnosis: "Preparing diagnostics. Do not use the phone for a few seconds…", recordingInProgress: "Recording in progress", reproduceFinish: "Reproduce the issue on the phone. When it happens, return to this page and click “Finished”.", warningSeconds: "Warning: {{seconds}} seconds remaining. Collection will stop automatically at 2 minutes.", finished: "Finished", savingTechnical: "Saving the recording and technical logs…", collectionComplete: "Collection complete.", filesNextStep: "The files will be submitted with the case in the next step.", technicalDetails: "Technical details",
    privacyTitle: "BRTE privacy", privacyP1: "Your name, email, phone number, postal address, country, device information, IMEI or serial number and purchase date when provided, issue description, and the evidence you choose are associated with the case. Assisted collection may include screen recording, technical logs, and device metadata.", privacyP2: "Close personal conversations, passwords, and documents before recording. Collection starts only after your authorization.", loading: "Loading…",
  },
  "es-419": {
    unavailableFile: "Archivo no disponible.", loadingCase: "Cargando caso…", back: "Volver",
    customerReport: "Reporte del cliente", expectedBehavior: "Comportamiento esperado", notProvided: "No informado", software: "Software", carrier: "Operador", category: "Categoría", systemApps: "Sistema y aplicaciones", hardware: "Hardware",
    evidence: "Evidencias", noEvidence: "Todavía no se han enviado archivos.", download: "Descargar", addFile: "Agregar archivo", uploadingFile: "Enviando {{name}} · {{progress}}%", uploadFailed: "No fue posible enviar el archivo. Inténtalo de nuevo sin salir de esta página.", computerEvidence: "Recopilaciones por computadora", captureSessions: "Sesiones de captura", noCaptureSessions: "No hay una recopilación por computadora asociada.",
    supportCase: "Caso", customer: "Cliente", email: "Correo electrónico", receivedAt: "Recibido el", owner: "Responsable", unassigned: "Aún no asignado", status: "Estado", priority: "Prioridad", assign: "Asignar",
    updates: "Actualizaciones", caseReceived: "Caso recibido", dataUpdated: "Datos actualizados", visibleUpdate: "Actualización visible para el cliente", publishUpdate: "Publicar actualización", nextStepTitle: "Qué sucede ahora", nextReceived: "Recibimos tu caso. No necesitas hacer nada por ahora; comenzaremos a revisar la información enviada.", nextReviewing: "Tu caso está en análisis. Mantén disponibles tus canales de contacto por si el equipo necesita confirmar algo.", nextAwaitingCustomer: "Necesitamos algo de tu parte. Revisa la actualización más reciente y agrega la evidencia solicitada si es necesario.", nextResolved: "Este caso fue finalizado. Revisa las actualizaciones para consultar la resolución informada.",
    warrantyData: "Evaluación de garantía", warrantyStatus: "Posible garantía", warrantyYes: "Sí", warrantyNo: "No", warrantyUnsure: "No informado / no estoy seguro", deviceIdentifier: "IMEI / número de serie", purchaseDate: "Fecha de compra", replyTitle: "Responder a soporte", replyText: "Escribe la información solicitada por el equipo. También puedes agregar una evidencia arriba si es necesario.", replyPlaceholder: "Escribe tu respuesta aquí…", sendReply: "Enviar respuesta", replySending: "Enviando…", replySent: "Respuesta enviada. Nuestro equipo podrá continuar el análisis en este caso.", replyFailed: "No fue posible enviar tu respuesta. Inténtalo de nuevo sin salir de esta página.", customerReplyLabel: "Respuesta del cliente",
    trackingEyebrow: "SEGUIMIENTO", trackingTitle: "Tu caso, aquí.", trackingText: "Usa los datos que recibiste al finalizar el caso.", protocol: "Número de caso", accessCode: "Código de acceso", viewCase: "Consultar caso",
    staffArea: "ÁREA DEL EQUIPO", helloTfae: "Hola, equipo.", staffIntro: "Accede a los casos y evidencias de los clientes según tu perfil.", staffEmail: "Correo corporativo", password: "Contraseña", signingIn: "Ingresando…", accessDashboard: "Abrir panel", sendCode: "Enviar código", sendingCode: "Enviando código…", codeSentTitle: "Código enviado", codeSentText: "Enviamos un código de 6 dígitos a este correo. Vence en 10 minutos.", staffAccessCode: "Código de acceso", codeDigitsHint: "Ingresa los 6 números recibidos por correo.", verifyCode: "Validar e ingresar", verifyingCode: "Validando…", trustDevice: "Confiar en este dispositivo durante 7 días", trustDeviceHint: "Úsalo solo en una computadora personal o corporativa de uso exclusivo. Después de 7 días se solicitará un nuevo código.", resendCode: "Reenviar código", useDifferentEmail: "Usar otro correo", authRequestFailed: "No fue posible enviar el código ahora. Inténtalo de nuevo.", authVerifyFailed: "El código es inválido, venció o fue bloqueado. Solicita uno nuevo e inténtalo otra vez.", emailCodeUnavailable: "El acceso por código de correo aún no está configurado. Usa la contraseña temporalmente.", authPasswordFailed: "No fue posible ingresar con esas credenciales.", emergencyAccess: "Acceso de contingencia", emergencyAccessTitle: "Acceso de contingencia TFAE", emergencyAccessText: "Usa este acceso solamente si el código por correo no está disponible. La credencial debe mantenerse de forma segura por el equipo.", backToEmailCode: "Volver al código por correo",
    workspaceEyebrow: "BRTE WORKSPACE / RESUMEN", workspaceTitle: "Cada caso merece atención.", workspaceIntro: "Organiza el análisis. Conecta las evidencias. Da seguimiento a la solución.", signedInAs: "Conectado como", roleTfae: "TFAE", roleManager: "Manager", managerReadOnlyTitle: "Acceso de seguimiento", managerReadOnlyText: "Como Manager, puedes supervisar casos, responsables, evidencias e historial. Los cambios operativos permanecen con los TFAE.", logout: "Salir",
    totalCases: "Total de casos", awaitingAnalysis: "Pendientes de análisis", inReview: "En análisis", resolvedCases: "Resueltos", teamMonitoring: "Seguimiento de los TFAE", activeCases: "casos activos", assignedCases: "asignados", caseCenter: "Centro de casos", refresh: "Actualizar", filterStatus: "Filtrar por estado", all: "Todos",
    searchCases: "Buscar casos", searchPlaceholder: "Buscar caso, modelo, cliente…", caseProblem: "CASO / PROBLEMA", device: "DISPOSITIVO", received: "RECIBIDO", openCase: "Abrir {{problem}}",
    noSearchResults: "Ningún caso coincide con la búsqueda.", readyFirstCase: "Todo listo para el primer caso.", tryAnotherSearch: "Prueba otro término o filtro.", casesWillAppear: "Los casos enviados por los clientes aparecerán aquí.",
    priorityNormal: "Normal", priorityHigh: "Alta", priorityUrgent: "Urgente",
    statusReceived: "Recibido", statusReviewing: "En análisis", statusAwaitingCustomer: "Esperando al cliente", statusResolved: "Resuelto", statusRecording: "Grabando", statusComplete: "Completada", statusPartial: "Evidencia parcial", statusFailed: "Falló la recopilación", statusInterrupted: "Captura interrumpida", statusAwaitingYlog: "Esperando que se detengan los logs", statusFinalizing: "Finalizando", statusStarting: "Iniciando",
    assistedEyebrow: "DIAGNÓSTICO ASISTIDO", assistedTitle: "Tu celular. Nuestra atención.", assistedIntro: "Reproduce el problema mientras reunimos la información necesaria para el análisis.", localConnected: "Soporte local conectado", waitingConnection: "Esperando conexión",
    connectStep: "01 / CONECTAR", prepareComputer: "Prepara la computadora.", prepareComputerText: "Abre Support Bridge en Windows y conecta el celular con un cable USB de datos.", installBridge: "Instalar y abrir Support Bridge", initialSetup: "Configuración inicial en la computadora", connectionCode: "Código de conexión del programa", connectionCodePlaceholder: "Pega el código que aparece al abrir el programa", connect: "Conectar",
    authorizeStep: "02 / AUTORIZAR", connectDevice: "Conecta tu dispositivo.", authorizeText: "Activa la depuración USB y acepta la autorización en el celular.", viewImageInstructions: "Ver instrucciones con imágenes", noDevice: "No se detectó ningún dispositivo", dataCableHint: "Usa un cable de datos y mantén la pantalla desbloqueada.", authorizeComputer: "Autoriza esta computadora en el dispositivo", deviceOffline: "Dispositivo sin conexión", authorized: "Autorizado", platform: "Plataforma", unknownPlatform: "No reconocida",
    associateStep: "03 / VINCULAR AL CASO", oneCaseMany: "Un caso, varias reproducciones.", caseProtocol: "Número del caso", caseAccessCode: "Código de acceso al caso", autoUpload: "Enviar automáticamente las capturas finalizadas a este caso.",
    reproductionArea: "ÁREA DE REPRODUCCIÓN", captureRunning: "Captura en curso", readyToView: "Listo para visualizar", letsConnect: "Conectemos tu celular.", reproduceThenStop: "Reproduce el problema en el dispositivo. Cuando termines, detén la captura.", mirrorText: "La visualización del celular se abre en una ventana de la computadora.", openView: "Abrir visualización", ylogStarted: "Ya inicié la recopilación de YLog en el dispositivo.", captureConsent: "Autorizo la grabación de pantalla y la recopilación de registros técnicos para esta reproducción.", startCapture: "Iniciar captura", stopYlogText: "La grabación de pantalla ya se detuvo. Detén YLog en el dispositivo para continuar.", ylogStoppedCollect: "Ya detuve los logs — recopilar archivos", finishingValidating: "Finalizando y validando…", stopSave: "Detener y guardar captura",
    capturesThisComputer: "Capturas de esta computadora", capturesAppear: "Tus reproducciones aparecerán aquí. Cada una genera un paquete independiente.", uploadedTo: "Enviado a {{caseId}}", sendToCase: "Enviar al caso", noComputerConnection: "¿Sin computadora o conexión?", continueMobileGuide: "Continúa con la guía usando solo el celular.", localSupportInterrupted: "Se interrumpió la conexión con el soporte local. Revisa el programa en la computadora.",
    browserAutoAvailable: "La recopilación automática está disponible en Chrome o Edge.", browserOpenDesktop: "Abre esta página en una computadora con Chrome o Microsoft Edge. No se requiere instalación.", browserDirect: "RECOPILACIÓN DIRECTA DESDE EL NAVEGADOR", connectPhone: "Conecta tu celular", usbHint: "Prepara el dispositivo y sigue los pasos a continuación para conectarlo.", beforeConnectTitle: "Antes de conectar", beforeConnectCable: "Usa un cable USB que también transfiera datos.", beforeConnectUnlock: "Mantén el celular desbloqueado y deja esta página abierta.", beforeConnectPermission: "Cuando el celular pida permiso para esta conexión, acéptalo para continuar.", beforeConnectHelp: "Si no aparece nada, vuelve a conectar el cable y confirma que sea un cable de datos.", developerSetupTitle: "Prepara tu celular una sola vez", developerSetupText: "Para que el navegador pueda conectarse al celular, activa el Modo desarrollador y la Depuración USB. Activar estas opciones no borra tus archivos.", developerGuideTitle: "Cómo activar el Modo desarrollador y la Depuración USB", developerStep1: "Abre Configuración y entra en Acerca del teléfono.", developerStep2: "Toca 7 veces Número de compilación / Build number hasta que el celular confirme que el Modo desarrollador está activado.", developerStep3: "Vuelve a Configuración y abre Sistema → Opciones de desarrollador. En algunos modelos, esta opción aparece directamente en Configuración.", developerStep4: "Activa Depuración USB y confirma el aviso de Android.", developerStep5: "Conecta el celular a la computadora usando un cable USB que transfiera datos.", developerStep6: "Cuando aparezca “¿Permitir depuración USB? / Allow USB debugging?”, toca Permitir / OK.", developerMenuNote: "Los nombres de los menús pueden variar un poco según el modelo y la versión de Android.", developerAfterUse: "Después del soporte, puedes desactivar nuevamente la Depuración USB.", tutorialBadge: "VIDEO TUTORIAL", tutorialTitle: "Mira cómo preparar tu celular", tutorialText: "Mira el video mientras sigues los pasos. Muestra dónde activar la Depuración USB y confirmar el acceso.", tutorialPrivacy: "El video fue recortado para mostrar solamente los pasos necesarios.", tutorialLoading: "Preparando el video…", tutorialUnavailable: "No fue posible cargar el video. Sigue los pasos escritos y continúa normalmente.", tutorialNoAudio: "El video no tiene audio. Usa los pasos escritos como referencia principal.", connecting: "Conectando…", redoAuthorization: "Intentar la conexión nuevamente",
    maxTwoMinutes: "Límite máximo: 2 minutos.", twoMinuteHint: "Después de iniciar, reproduce el problema inmediatamente y finaliza en cuanto ocurra. Al llegar a 2 minutos, la recopilación se detendrá automáticamente y deberás intentarlo de nuevo.", browserConsent: "Autorizo la grabación de pantalla y la recopilación de registros técnicos únicamente para analizar este problema.", startCollection: "Iniciar recopilación", preparingDiagnosis: "Preparando el diagnóstico. No uses el celular durante unos segundos…", recordingInProgress: "Grabación en curso", reproduceFinish: "Reproduce el problema en el celular. Cuando ocurra, vuelve a esta página y pulsa “Terminé”.", warningSeconds: "Atención: quedan {{seconds}} segundos. La recopilación se detendrá automáticamente a los 2 minutos.", finished: "Terminé", savingTechnical: "Guardando la grabación y los registros técnicos…", collectionComplete: "Recopilación completada.", filesNextStep: "Los archivos se enviarán junto con el caso en el siguiente paso.", technicalDetails: "Detalles técnicos",
    privacyTitle: "Privacidad de BRTE", privacyP1: "Tu nombre, correo electrónico, teléfono, dirección postal, país, información del dispositivo, IMEI o número de serie y fecha de compra cuando los informes, descripción del problema y las evidencias que elijas quedan asociados al caso. La recopilación asistida puede incluir grabación de pantalla, registros técnicos y metadatos del dispositivo.", privacyP2: "Cierra conversaciones personales, contraseñas y documentos antes de grabar. La recopilación solo comienza después de tu autorización.", loading: "Cargando…",
  },
  "zh-CN": {
    unavailableFile: "文件不可用。", loadingCase: "正在加载服务单…", back: "返回",
    customerReport: "客户问题描述", expectedBehavior: "预期行为", notProvided: "未提供", software: "软件", carrier: "运营商", category: "类别", systemApps: "系统和应用", hardware: "硬件",
    evidence: "证据", noEvidence: "尚未提交文件。", download: "下载", addFile: "添加文件", uploadingFile: "正在上传 {{name}} · {{progress}}%", uploadFailed: "文件上传失败。请不要离开此页面并重试。", computerEvidence: "电脑采集", captureSessions: "采集会话", noCaptureSessions: "该服务单没有关联的电脑采集记录。",
    supportCase: "服务单", customer: "客户", email: "电子邮箱", receivedAt: "接收时间", owner: "负责人", unassigned: "尚未分配", status: "状态", priority: "优先级", assign: "分配",
    updates: "更新记录", caseReceived: "服务单已接收", dataUpdated: "数据已更新", visibleUpdate: "客户可见的更新", publishUpdate: "发布更新", nextStepTitle: "接下来会发生什么", nextReceived: "我们已收到您的服务单。目前无需操作，我们会开始审核您提交的信息。", nextReviewing: "您的服务单正在审核中。请保持联系方式可用，以便团队需要时确认信息。", nextAwaitingCustomer: "我们需要您补充信息。请查看下面最新的更新，并在需要时添加所要求的证据。", nextResolved: "此服务单已完成。请查看下面的更新以了解处理结果。",
    warrantyData: "保修初步信息", warrantyStatus: "可能的保修", warrantyYes: "是", warrantyNo: "否", warrantyUnsure: "未提供 / 不确定", deviceIdentifier: "IMEI / 序列号", purchaseDate: "购买日期", replyTitle: "回复支持团队", replyText: "请填写支持团队要求的信息。如有需要，也可以在上方添加证据。", replyPlaceholder: "在此输入回复…", sendReply: "发送回复", replySending: "正在发送…", replySent: "回复已发送。支持团队可以在此服务单中继续审核。", replyFailed: "回复发送失败。请不要离开此页面并重试。", customerReplyLabel: "客户回复",
    trackingEyebrow: "服务单跟踪", trackingTitle: "在这里查看您的服务单。", trackingText: "请使用提交服务单时收到的信息进行查询。", protocol: "服务单号", accessCode: "访问码", viewCase: "查看服务单",
    staffArea: "团队区域", helloTfae: "您好，团队成员。", staffIntro: "根据您的角色查看客户服务单和证据。", staffEmail: "企业邮箱", password: "密码", signingIn: "正在登录…", accessDashboard: "进入面板", sendCode: "发送验证码", sendingCode: "正在发送验证码…", codeSentTitle: "验证码已发送", codeSentText: "我们已向此邮箱发送 6 位验证码。验证码将在 10 分钟后过期。", staffAccessCode: "访问验证码", codeDigitsHint: "请输入邮件中收到的 6 位数字。", verifyCode: "验证并登录", verifyingCode: "正在验证…", trustDevice: "信任此设备 7 天", trustDeviceHint: "仅在您个人使用或专用的公司电脑上启用。7 天后将再次要求验证码。", resendCode: "重新发送验证码", useDifferentEmail: "使用其他邮箱", authRequestFailed: "目前无法发送验证码，请重试。", authVerifyFailed: "验证码无效、已过期或已被锁定。请申请新的验证码后重试。", emailCodeUnavailable: "邮件验证码登录尚未配置，请暂时使用密码。", authPasswordFailed: "无法使用这些凭据登录。", emergencyAccess: "应急访问", emergencyAccessTitle: "TFAE 应急访问", emergencyAccessText: "仅在邮件验证码服务不可用时使用。应急凭据必须由团队安全保管。", backToEmailCode: "返回邮件验证码",
    workspaceEyebrow: "BRTE WORKSPACE / 概览", workspaceTitle: "每个服务单都值得关注。", workspaceIntro: "组织分析、关联证据并跟进解决方案。", signedInAs: "当前登录", roleTfae: "TFAE", roleManager: "Manager", managerReadOnlyTitle: "监督访问", managerReadOnlyText: "作为 Manager，您可以查看服务单、负责人、证据和历史记录。状态、优先级、分配和操作性更新由 TFAE 处理。", logout: "退出登录",
    totalCases: "服务单总数", awaitingAnalysis: "等待分析", inReview: "分析中", resolvedCases: "已解决", teamMonitoring: "TFAE 跟进概览", activeCases: "个进行中的服务单", assignedCases: "个已分配", caseCenter: "服务单中心", refresh: "刷新", filterStatus: "按状态筛选", all: "全部",
    searchCases: "搜索服务单", searchPlaceholder: "搜索服务单、型号、客户…", caseProblem: "服务单 / 问题", device: "设备", received: "接收时间", openCase: "打开 {{problem}}",
    noSearchResults: "没有符合搜索条件的服务单。", readyFirstCase: "已准备好接收第一个服务单。", tryAnotherSearch: "请尝试其他关键词或筛选条件。", casesWillAppear: "客户提交的服务单会显示在这里。",
    priorityNormal: "普通", priorityHigh: "高", priorityUrgent: "紧急",
    statusReceived: "已接收", statusReviewing: "分析中", statusAwaitingCustomer: "等待客户", statusResolved: "已解决", statusRecording: "录制中", statusComplete: "已完成", statusPartial: "部分证据", statusFailed: "采集失败", statusInterrupted: "采集中断", statusAwaitingYlog: "等待日志停止", statusFinalizing: "正在完成", statusStarting: "正在启动",
    assistedEyebrow: "辅助诊断", assistedTitle: "您的手机，我们认真处理。", assistedIntro: "请复现问题，我们会同时收集分析所需的信息。", localConnected: "本地支持已连接", waitingConnection: "等待连接",
    connectStep: "01 / 连接", prepareComputer: "准备电脑。", prepareComputerText: "在 Windows 上打开 Support Bridge，并使用 USB 数据线连接手机。", installBridge: "安装并打开 Support Bridge", initialSetup: "电脑初始设置", connectionCode: "程序连接码", connectionCodePlaceholder: "粘贴程序打开时显示的代码", connect: "连接",
    authorizeStep: "02 / 授权", connectDevice: "连接您的设备。", authorizeText: "启用 USB 调试，并在手机上接受授权。", viewImageInstructions: "查看图示说明", noDevice: "未检测到设备", dataCableHint: "请使用数据线并保持屏幕解锁。", authorizeComputer: "请在设备上授权此电脑", deviceOffline: "设备离线", authorized: "已授权", platform: "平台", unknownPlatform: "无法识别",
    associateStep: "03 / 关联服务单", oneCaseMany: "一个服务单可以包含多次复现。", caseProtocol: "服务单号", caseAccessCode: "服务单访问码", autoUpload: "自动将完成的采集上传到此服务单。",
    reproductionArea: "问题复现区域", captureRunning: "正在采集", readyToView: "可以查看", letsConnect: "请先连接您的手机。", reproduceThenStop: "请在设备上复现问题。完成后停止采集。", mirrorText: "手机画面会在电脑窗口中打开。", openView: "打开画面", ylogStarted: "我已经在设备上启动了 YLog 采集。", captureConsent: "我授权为本次问题复现进行屏幕录制和技术日志采集。", startCapture: "开始采集", stopYlogText: "屏幕录制已经停止。请在设备上停止 YLog 后继续。", ylogStoppedCollect: "我已停止日志 — 收集文件", finishingValidating: "正在完成并验证…", stopSave: "停止并保存采集",
    capturesThisComputer: "此电脑的采集记录", capturesAppear: "您的复现记录会显示在这里。每次采集都会生成独立的数据包。", uploadedTo: "已上传到 {{caseId}}", sendToCase: "发送到服务单", noComputerConnection: "没有电脑或连接？", continueMobileGuide: "请使用仅手机模式的指南继续。", localSupportInterrupted: "与本地支持程序的连接已中断。请检查电脑上的程序。",
    browserAutoAvailable: "Chrome 或 Edge 支持自动采集。", browserOpenDesktop: "请在电脑上使用 Chrome 或 Microsoft Edge 打开此页面。无需安装额外程序。", browserDirect: "浏览器直接采集", connectPhone: "连接手机", usbHint: "请先准备好手机，然后按照下面的步骤连接。", beforeConnectTitle: "连接之前", beforeConnectCable: "请使用支持数据传输的 USB 数据线。", beforeConnectUnlock: "保持手机解锁，并保持此页面打开。", beforeConnectPermission: "手机出现连接授权提示时，请允许以继续。", beforeConnectHelp: "如果没有出现提示，请重新插拔数据线，并确认数据线支持数据传输。", developerSetupTitle: "只需准备手机一次", developerSetupText: "为了让浏览器连接手机，请开启开发者模式和 USB 调试。开启这些选项不会删除您的文件。", developerGuideTitle: "如何开启开发者模式和 USB 调试", developerStep1: "打开“设置”，进入“关于手机”。", developerStep2: "连续点击“版本号 / Build number”7 次，直到手机提示开发者模式已开启。", developerStep3: "返回“设置”，打开“系统 → 开发者选项”。部分机型会直接在“设置”中显示“开发者选项”。", developerStep4: "开启“USB 调试”，并确认 Android 提示。", developerStep5: "使用支持数据传输的 USB 数据线将手机连接到电脑。", developerStep6: "出现“允许 USB 调试？/ Allow USB debugging?”时，请点击“允许 / OK”。", developerMenuNote: "不同机型和 Android 版本的菜单名称可能略有不同。", developerAfterUse: "本次支持结束后，您可以再次关闭 USB 调试。", tutorialBadge: "视频教程", tutorialTitle: "查看如何准备手机", tutorialText: "您可以边看视频边操作。视频会展示如何开启 USB 调试并确认访问。", tutorialPrivacy: "视频已剪辑，仅保留本流程所需的操作步骤。", tutorialLoading: "正在准备视频…", tutorialUnavailable: "视频无法加载。请按照旁边的文字步骤继续操作。", tutorialNoAudio: "视频没有声音，请以文字步骤为主要参考。", connecting: "正在连接…", redoAuthorization: "重新尝试连接",
    maxTwoMinutes: "最长 2 分钟。", twoMinuteHint: "开始后请立即复现问题，并在问题出现后尽快结束。达到 2 分钟时采集会自动停止，需要重新尝试。", browserConsent: "我授权仅为分析此问题进行屏幕录制和技术日志采集。", startCollection: "开始采集", preparingDiagnosis: "正在准备诊断，请暂时不要操作手机…", recordingInProgress: "正在录制", reproduceFinish: "请在手机上复现问题。问题出现后返回此页面并点击“完成”。", warningSeconds: "注意：还剩 {{seconds}} 秒。采集将在 2 分钟时自动停止。", finished: "完成", savingTechnical: "正在保存录制和技术日志…", collectionComplete: "采集完成。", filesNextStep: "文件将在下一步随服务单一起提交。", technicalDetails: "技术详情",
    privacyTitle: "BRTE 隐私说明", privacyP1: "您的姓名、电子邮箱、电话号码、邮政地址、国家/地区、设备信息，以及您主动提供的 IMEI 或序列号和购买日期、问题描述和所选证据会与服务单关联。辅助采集可能包括屏幕录制、技术日志和设备元数据。", privacyP2: "录制前请关闭私人聊天、密码和文档。只有在您授权后才会开始采集。", loading: "正在加载…",
  },
};

export function portalUi(language?: string) {
  const lang = resolveLanguage(language);
  return copy[lang];
}

export function portalDateLocale(language?: string) {
  return localeMap[resolveLanguage(language)];
}

export function portalStatus(language: string | undefined, status: string) {
  const c = portalUi(language);
  const key: Record<string, string> = {
    received: "statusReceived", reviewing: "statusReviewing", awaiting_customer: "statusAwaitingCustomer", resolved: "statusResolved",
    recording: "statusRecording", complete: "statusComplete", partial: "statusPartial", failed: "statusFailed", interrupted: "statusInterrupted",
    awaiting_ylog_stop: "statusAwaitingYlog", finalizing: "statusFinalizing", starting: "statusStarting",
  };
  return c[key[status]] || status;
}

export function portalPriority(language: string | undefined, priority: string) {
  const c = portalUi(language);
  if (priority === "high") return c.priorityHigh;
  if (priority === "urgent") return c.priorityUrgent;
  return c.priorityNormal;
}

export function uiFormat(value: string, vars: Record<string, string | number>) {
  let output = value;
  for (const [name, replacement] of Object.entries(vars)) output = output.replace(`{{${name}}}`, String(replacement));
  return output;
}
